USE typequest;

-- Inimigos em ordem crescente de dificuldade
INSERT INTO INIMIGO (nome, sprite, nivel_minimo, hp, dano_base, tipo) VALUES
('Esqueleto Comum',    '💀', 1, 60,  8,  'esqueleto'),
('Zumbi Arcano',       '🧟', 1, 80,  10, 'zumbi'),
('Ogro das Runas',     '👹', 2, 120, 15, 'ogro'),
('Troll das Sombras',  '🧌', 3, 150, 18, 'troll'),
('Dragão Corrupto',    '🐉', 3, 200, 25, 'dragao'),
('Liche Negro',        '☠️', 4, 180, 22, 'chefe'),
('Dragão de Gelo',     '❄️', 5, 250, 30, 'chefe');

-- Palavras dificuldade 1 (3-4 letras, fáceis)
INSERT INTO PALAVRA (texto, dificuldade, idioma) VALUES
('fogo', 1, 'pt-BR'),
('agua', 1, 'pt-BR'),
('lua', 1, 'pt-BR'),
('sol', 1, 'pt-BR'),
('rei', 1, 'pt-BR'),
('mago', 1, 'pt-BR'),
('elfo', 1, 'pt-BR'),
('orc', 1, 'pt-BR'),
('fer', 1, 'pt-BR'),
('ouro', 1, 'pt-BR'),
('gelo', 1, 'pt-BR'),
('vento', 1, 'pt-BR'),
('alma', 1, 'pt-BR'),
('raio', 1, 'pt-BR'),
('arco', 1, 'pt-BR'),
('luta', 1, 'pt-BR'),
('mort', 1, 'pt-BR'),
('cura', 1, 'pt-BR'),
('runa', 1, 'pt-BR'),
('clan', 1, 'pt-BR'),
('deus', 1, 'pt-BR'),
('lodo', 1, 'pt-BR'),
('breu', 1, 'pt-BR'),
('povo', 1, 'pt-BR'),
('arma', 1, 'pt-BR'),
('vale', 1, 'pt-BR'),
('boss', 1, 'pt-BR'),
('rank', 1, 'pt-BR'),
('mina', 1, 'pt-BR'),
('lago', 1, 'pt-BR'),
('fera', 1, 'pt-BR'),
('caos', 1, 'pt-BR'),
('faca', 1, 'pt-BR'),
('lama', 1, 'pt-BR'),
('fada', 1, 'pt-BR'),
('orbe', 1, 'pt-BR'),
('naga', 1, 'pt-BR'),
('anao', 1, 'pt-BR'),
('gema', 1, 'pt-BR'),
('saga', 1, 'pt-BR');

-- Palavras dificuldade 2 (5-6 letras, médio)
INSERT INTO PALAVRA (texto, dificuldade, idioma) VALUES
('espada', 2, 'pt-BR'),
('escudo', 2, 'pt-BR'),
('torre', 2, 'pt-BR'),
('flecha', 2, 'pt-BR'),
('pedra', 2, 'pt-BR'),
('chamas', 2, 'pt-BR'),
('bruxo', 2, 'pt-BR'),
('duelo', 2, 'pt-BR'),
('heroi', 2, 'pt-BR'),
('magia', 2, 'pt-BR'),
('poder', 2, 'pt-BR'),
('manto', 2, 'pt-BR'),
('crise', 2, 'pt-BR'),
('tribo', 2, 'pt-BR'),
('relva', 2, 'pt-BR'),
('setas', 2, 'pt-BR'),
('lanca', 2, 'pt-BR'),
('vidro', 2, 'pt-BR'),
('titan', 2, 'pt-BR'),
('alixa', 2, 'pt-BR'),
('troxa', 2, 'pt-BR'),
('cobra', 2, 'pt-BR'),
('forca', 2, 'pt-BR'),
('runas', 2, 'pt-BR'),
('garra', 2, 'pt-BR'),
('porao', 2, 'pt-BR'),
('bolsa', 2, 'pt-BR'),
('gruta', 2, 'pt-BR'),
('altar', 2, 'pt-BR'),
('golpe', 2, 'pt-BR'),
('elmo', 2, 'pt-BR'),
('elfos', 2, 'pt-BR'),
('orcos', 2, 'pt-BR'),
('gnomo', 2, 'pt-BR'),
('duende', 2, 'pt-BR'),
('fauno', 2, 'pt-BR'),
('demonio', 2, 'pt-BR'),
('dragao', 2, 'pt-BR'),
('golem', 2, 'pt-BR'),
('totem', 2, 'pt-BR');

-- Palavras dificuldade 3 (7-8 letras, difícil)
INSERT INTO PALAVRA (texto, dificuldade, idioma) VALUES
('masmorra', 3, 'pt-BR'),
('cavaleiro', 3, 'pt-BR'),
('feitico', 3, 'pt-BR'),
('guerreiro', 3, 'pt-BR'),
('magister', 3, 'pt-BR'),
('alquimia', 3, 'pt-BR'),
('batalha', 3, 'pt-BR'),
('cruzada', 3, 'pt-BR'),
('oraculo', 3, 'pt-BR'),
('profeta', 3, 'pt-BR'),
('floresta', 3, 'pt-BR'),
('cristal', 3, 'pt-BR'),
('arsenal', 3, 'pt-BR'),
('artefato', 3, 'pt-BR'),
('templo', 3, 'pt-BR'),
('samurai', 3, 'pt-BR'),
('paladino', 3, 'pt-BR'),
('xamanismo', 3, 'pt-BR'),
('sombras', 3, 'pt-BR'),
('basilisco', 3, 'pt-BR'),
('grifo', 3, 'pt-BR'),
('quimera', 3, 'pt-BR'),
('cataclismo', 3, 'pt-BR'),
('portao', 3, 'pt-BR'),
('labirinto', 3, 'pt-BR'),
('catacomba', 3, 'pt-BR'),
('dungeon', 3, 'pt-BR'),
('minotauro', 3, 'pt-BR'),
('centauro', 3, 'pt-BR'),
('ciclope', 3, 'pt-BR'),
('hidra', 3, 'pt-BR'),
('phoenix', 3, 'pt-BR'),
('grifo', 3, 'pt-BR'),
('kraken', 3, 'pt-BR'),
('leviatao', 3, 'pt-BR'),
('banshee', 3, 'pt-BR'),
('vampiro', 3, 'pt-BR'),
('licantropo', 3, 'pt-BR'),
('zumbi', 3, 'pt-BR'),
('espectro', 3, 'pt-BR');

-- Palavras dificuldade 4 (9-10 letras, muito difícil)
INSERT INTO PALAVRA (texto, dificuldade, idioma) VALUES
('invocacao', 4, 'pt-BR'),
('necromante', 4, 'pt-BR'),
('labirinto', 4, 'pt-BR'),
('venomancro', 4, 'pt-BR'),
('iluminacao', 4, 'pt-BR'),
('destruicao', 4, 'pt-BR'),
('cavaleiros', 4, 'pt-BR'),
('guerreiros', 4, 'pt-BR'),
('feiticeiro', 4, 'pt-BR'),
('encantador', 4, 'pt-BR'),
('abominacao', 4, 'pt-BR'),
('ressureicao', 4, 'pt-BR'),
('profanacao', 4, 'pt-BR'),
('transformar', 4, 'pt-BR'),
('purificacao', 4, 'pt-BR'),
('corrompido', 4, 'pt-BR'),
('maldicionado', 4, 'pt-BR'),
('supremacia', 4, 'pt-BR'),
('dominacao', 4, 'pt-BR'),
('mortificado', 4, 'pt-BR'),
('amaldicoado', 4, 'pt-BR'),
('perseguicao', 4, 'pt-BR'),
('manifestacao', 4, 'pt-BR'),
('convocacao', 4, 'pt-BR'),
('banimento', 4, 'pt-BR'),
('elemental', 4, 'pt-BR'),
('transmutacao', 4, 'pt-BR'),
('conjuracao', 4, 'pt-BR'),
('misticismo', 4, 'pt-BR'),
('ocultismo', 4, 'pt-BR'),
('necromancia', 4, 'pt-BR'),
('telecinese', 4, 'pt-BR'),
('clarividencia', 4, 'pt-BR'),
('arcanismo', 4, 'pt-BR'),
('elementalismo', 4, 'pt-BR'),
('ilusion', 4, 'pt-BR'),
('transmutador', 4, 'pt-BR'),
('invocador', 4, 'pt-BR'),
('destruidor', 4, 'pt-BR'),
('protetor', 4, 'pt-BR');

-- Palavras dificuldade 5 (11+ letras, extremo)
INSERT INTO PALAVRA (texto, dificuldade, idioma) VALUES
('apocalipse', 5, 'pt-BR'),
('corrompacao', 5, 'pt-BR'),
('encantamento', 5, 'pt-BR'),
('abominacao', 5, 'pt-BR'),
('exterminacao', 5, 'pt-BR'),
('predestinacao', 5, 'pt-BR'),
('transcendencia', 5, 'pt-BR'),
('imortalidade', 5, 'pt-BR'),
('obscurantismo', 5, 'pt-BR'),
('onipotencia', 5, 'pt-BR'),
('omnisciencia', 5, 'pt-BR'),
('omnipresenca', 5, 'pt-BR'),
('predestinado', 5, 'pt-BR'),
('ressurgimento', 5, 'pt-BR'),
('desmaterializacao', 5, 'pt-BR'),
('superpoderes', 5, 'pt-BR'),
('metamorfose', 5, 'pt-BR'),
('reencarnacao', 5, 'pt-BR'),
('misticidade', 5, 'pt-BR'),
('transcendental', 5, 'pt-BR'),
('impenetravel', 5, 'pt-BR'),
('invulneravel', 5, 'pt-BR'),
('inquebravel', 5, 'pt-BR'),
('indestrutivel', 5, 'pt-BR'),
('contramagica', 5, 'pt-BR'),
('antimagia', 5, 'pt-BR'),
('superioridade', 5, 'pt-BR'),
('singularidade', 5, 'pt-BR'),
('manifestacao', 5, 'pt-BR'),
('materializar', 5, 'pt-BR'),
('desmaterializar', 5, 'pt-BR'),
('transformacao', 5, 'pt-BR'),
('desencantamento', 5, 'pt-BR'),
('supermagia', 5, 'pt-BR'),
('megafeitico', 5, 'pt-BR'),
('ultrapoderoso', 5, 'pt-BR'),
('extraordinario', 5, 'pt-BR'),
('sobrenatural', 5, 'pt-BR'),
('supranatural', 5, 'pt-BR'),
('hipermagia', 5, 'pt-BR');
